---

- name: Craft An automated Ubuntu JeOS iso
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - settings.yml
  vars_prompt:
    - name: UserPassword
      prompt: "What is your user password"
      private: yes
  tasks:
    - file:
        path: tmpbuild/newiso
        state: directory
        mode: 0755

    - file:
        path: tmpbuild/origiso
        state: directory
        mode: 0755

    - file:
        path: tmpbuild/newiso/custom
        state: directory
        mode: 0755

    - name: mount src_iso
      become: true
      command: "mount -oloop,ro iso/{{ src_iso }} tmpbuild/origiso/"

    - name: rsync src_iso to tmp location for crafting dst_iso
      synchronize:
        src: tmpbuild/origiso/
        dest: tmpbuild/newiso

    - name: Customising syslinux - adding curses menu
      become: true
      copy:
        src: "../files/menu.c32"
        dest: "tmpbuild/newiso/isolinux/"

    - name: Customising grub2 - tuning menu
      become: true
      template:
        src: "../files/grub.cfg.j2"
        dest: "tmpbuild/newiso/boot/grub/grub.cfg"

    - name: Customising syslinux - tuning menu
      become: true
      template:
        src: "../files/isolinux.cfg.j2"
        dest: "tmpbuild/newiso/isolinux/isolinux.cfg"

    - stat: path="files/ssh.tar.gpg"
      register: sshtarball

    - set_fact:
        preseed_late_command: "cp /cdrom/custom/postinstall.sh /target/tmp/; in-target sh /tmp/postinstall.sh"
        when: sshtarball.stat.exists == False

    - set_fact:
        preseed_late_command: "cp /cdrom/custom/postinstall.sh /target/tmp/; cp /cdrom/custom/ssh.tar.gpg /target/home/{{ UserName }}; in-target sh /tmp/postinstall.sh"
      when: sshtarball.stat.exists == True

    - name: Copy postinstall script to iso
      become: true
      template:
        src: "../files/postinstall.sh.j2"
        dest: "tmpbuild/newiso/custom/postinstall.sh"
        mode: 0755

    - name: Adding our Pressed file - from template
      become: true
      template:
        src: "../files/{{ preseed_file }}.j2"
        dest: "tmpbuild/newiso/preseed/{{ preseed_file }}"

    - name: Adding our expert partition recipe
      become: true
      copy:
        src: "../files/{{ partitions_file }}"
        dest: "tmpbuild/newiso/custom/"

    - name: Add ssh keys encrypted tarball
      copy:
        src: "../files/ssh.tar.gpg"
        dest: "tmpbuild/newiso/custom/"
      when: sshtarball.stat.exists == True

    - name: generating dst_iso
      become: true
      command: "mkisofs -D -r -V 'PAJUNA_UBUNTU' -cache-inodes -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o '../../iso/{{ dst_iso }}' ."
      args:
        chdir: tmpbuild/newiso
        creates: "../../../iso/{{ dst_iso }}"

    - name: Making iso bootable on usb sticks
      become: true
      command: "isohybrid iso/{{ dst_iso }}"

    - name: Unmounting src_iso
      become: true
      command: "umount iso/{{ src_iso }}"

    - name: Cleaning up temp files
      become: true
      file: path=tmpbuild state=absent
      when: cleanup

    - debug: msg="New iso baked - iso/{{ dst_iso }}"
